In [1]:
import numpy as np
list1 = [[1,2,3], [4,5,6], [7,8,9]]
array1 = np.array(list1, dtype = 'int')
print(array1)
print()
array2 = array1.astype('int').astype('str')
print(array2)
print()
mylist = array2.tolist()
print(mylist)
print()
print()
print("The shape of the array is:", array1.shape)
print("The size of the array is:", array1.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[['1' '2' '3']
 ['4' '5' '6']
 ['7' '8' '9']]

[['1', '2', '3'], ['4', '5', '6'], ['7', '8', '9']]


The shape of the array is: (3, 3)
The size of the array is: 9


In [2]:
listx =[10,11,12]
newarr = np.array(listx,dtype = 'float')
print(newarr)
newarr = newarr+3
print(newarr)

[10. 11. 12.]
[13. 14. 15.]


In [3]:
list2 = [0,3,4,],[5,6,7],[8,9,10]
array3 = np.array(list2, dtype = 'float')
print(array3)
print()
boo = array3>=2
print(boo)


[[ 0.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]

[[False  True  True]
 [ True  True  True]
 [ True  True  True]]
